
import bails from "../assets/Bails.png";
import ballThrower from "../assets/Ball Thrower.png"
import guard from "../assets/Abdominal Guard.png";
import ball from "../assets/Ball.png";
import bat from "../assets/Bat.png";
import gloves from "../assets/Gloves.png";
import helmet from "../assets/Helmet.png";
import inners from "../assets/Inners.png";
import pad from "../assets/Pad.png";
import product14 from "../assets/product14.png";
import rough from "../assets/rough.jpg";
import Shoes from "../assets/Shoes.png";
import Stumps from "../assets/Stumps.png";
import thighGuard from "../assets/Thigh guard.png";
import keepingGloves from "../assets/Wicket Keeping Gloves.png";
import tshirt from "../assets/Tshirts.jpg";
import pant from "../assets/Pants.jpg";
export const dummyData= [{
    id:"1",
    imageUrl:bails,
    name:"Bails",
    price:"0.005",
    qty:"200",
    category:"Accessories",
    ratings:"4",
    reviews:"8.4",
    excellent:"7.6",
    comfort:"8.6",
    cleanliness:"8.2",
    chances:"8.9",
    easytouse:"9.0",
    accuracy:"8.2",
    valueformoney:"8.0"
},{
    id:"2",
    imageUrl:ballThrower,
    name:"Ball Thrower",
    price:"0.0074",
    qty:"100",
    category:"Accessories",
    ratings:"3",
    reviews:"7.6",
    excellent:"7.3",
    comfort:"7.4",
    cleanliness:"7.4",
    chances:"7.8",
    easytouse:"7.6",
    accuracy:"7.2",
    valueformoney:"7.2"
},{
    id:"3",
    imageUrl:guard,
    name:"Abdominal Guard",
    price:"0.0022",
    qty:"200",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"8.9",
    excellent:"9.2",
    comfort:"8,9",
    cleanliness:"8.4",
    chances:"8.4",
    easytouse:"8.7",
    accuracy:"8.8",
    valueformoney:"9.0"
},{
    id:"4",
    imageUrl:ball,
    name:"Ball",
    price:"0.015",
    qty:"1000",
    category:"Bats and Balls",
    ratings:"4",
    reviews:"9.1",
    excellent:"9.3",
    comfort:"9.5",
    cleanliness:"9.0",
    chances:"8.2",
    easytouse:"9.4",
    accuracy:"8.8",
    valueformoney:"8.7"
},{
    id:"5",
    imageUrl:bat,
    name:"Kashmiri Bat",
    price:"0.0543",
    qty:"500",
    category:"Bats and Balls",
    ratings:"5",
    reviews:"9.5",
    excellent:"9.8",
    comfort:"9.7",
    cleanliness:"9.6",
    chances:"8.0",
    easytouse:"9.5",
    accuracy:"8.5",
    valueformoney:"9.0"
},{
    id:"6",
    imageUrl:gloves,
    name:"Batting Gloves",
    price:"0.011",
    qty:"400",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"8.3",
    excellent:"8.5",
    comfort:"8.2",
    cleanliness:"8.1",
    chances:"8.4",
    easytouse:"8.5",
    accuracy:"8.1",
    valueformoney:"7.6"
},{
    id:"7",
    imageUrl:helmet,
    name:"Helmet",
    price:"0.037",
    qty:"200",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"7.9",
    excellent:"7.3",
    comfort:"8.0",
    cleanliness:"8.2",
    chances:"8.5",
    easytouse:"8.1",
    accuracy:"7.6",
    valueformoney:"7.3"
},{
    id:"8",
    imageUrl:inners,
    name:"Inners",
    price:"0.0037",
    qty:"400",
    category:"Cricket Kit",
    ratings:"3",
    reviews:"7.4",
    excellent:"6.9",
    comfort:"7.4",
    cleanliness:"7.3",
    chances:"8.5",
    easytouse:"8.1",
    accuracy:"8.1",
    valueformoney:"7.0"
},{
    id:"9",
    imageUrl:pad,
    name:"Pads",
    price:"0.022",
    qty:"400",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"8.8",
    excellent:"8.8",
    comfort:"8.2",
    cleanliness:"7.2",
    chances:"9.0",
    easytouse:"8.9",
    accuracy:"9.4",
    valueformoney:"8.8"
},{
    id:"10",
    imageUrl:product14,
    name:"Elbow Guard",
    price:"0.0030",
    qty:"200",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"8.6",
    excellent:"8.5",
    comfort:"8.6",
    cleanliness:"8.9",
    chances:"9.3",
    easytouse:"9.4",
    accuracy:"7.6",
    valueformoney:"8.0"
},{
    id:"11",
    imageUrl:Shoes,
    name:"Shoes",
    price:"0.026",
    qty:"400",
    category:"Cricket Shoes",
    ratings:"5",
    reviews:"9.6",
    excellent:"9.7",
    comfort:"9.8",
    cleanliness:"9.4",
    chances:"9.1",
    easytouse:"9.9",
    accuracy:"9.5",
    valueformoney:"9.7"
},{
    id:"12",
    imageUrl:Stumps,
    name:"Stumps",
    price:"0.018",
    qty:"300",
    category:"Accessories",
    ratings:"3",
    reviews:"7.4",
    excellent:"8.1",
    comfort:"7.4",
    cleanliness:"6.9",
    chances:"9.0",
    easytouse:"8.9",
    accuracy:"7.0",
    valueformoney:"6.5"
},{
    id:"13",
    imageUrl:thighGuard,
    name:"Thigh Guard",
    price:"0.015",
    qty:"200",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"8.5",
    excellent:"8.1",
    comfort:"9.0",
    cleanliness:"8.4",
    chances:"7.4",
    easytouse:"8.0",
    accuracy:"8.9",
    valueformoney:"9.4"
},{
    id:"14",
    imageUrl:keepingGloves,
    name:"Keeping Gloves",
    price:"0.015",
    qty:"100",
    category:"Cricket Kit",
    ratings:"4",
    reviews:"8.7",
    excellent:"8.6",
    comfort:"8.3",
    cleanliness:"8.9",
    chances:"8.9",
    easytouse:"9.5",
    accuracy:"8.0",
    valueformoney:"7.5"
},{
    id:"15",
    imageUrl:tshirt,
    name:"Tshirt",
    price:"0.0074",
    qty:"400",
    category:"Cricket Apparels",
    ratings:"5",
    reviews:"9.8",
    excellent:"9.8",
    comfort:"9.3",
    cleanliness:"9.5",
    chances:"8.8",
    easytouse:"9.9",
    accuracy:"9.9",
    valueformoney:"9.8"
},{
    id:"16",
    imageUrl:pant,
    name:"Pants",
    price:"0.0074",
    qty:"400",
    category:"Cricket Apparels",
    ratings:"4",
    reviews:"8.2",
    excellent:"8.4",
    comfort:"8.2",
    cleanliness:"7.9",
    chances:"8.0",
    easytouse:"7.8",
    accuracy:"8.3",
    valueformoney:"8.0"
}];
