export const Images = {
  logo: require('../assets/logo.png'),
  indiaFlag : require('../assets/TrafficSystem/indiaFlag.png'),
  australiaFlag: require('../assets/TrafficSystem/australiaFlag.png'),
  car:require('../assets/TrafficSystem/car.png'),
  Profile:require('../assets/TrafficSystem/profile.png'),
  whiteCar:require('../assets/TrafficSystem/whiteCar.png'),
  hotel:require('../assets/TrafficSystem/hotel.png'),
  location:require('../assets/TrafficSystem/location.png'),
  india: require('../assets/flags/india.png'),
  australia: require('../assets/flags/australia.png'),
  england: require('../assets/flags/england.png'),
  newzeland: require('../assets/flags/newzeland.png'),
  saudiarabia: require('../assets/flags/saudiarabia.png'),
  thailand: require('../assets/flags/thailand.png'),
  cardLocation: require('../assets/cardLocation.png'),
  menu: require('../assets/NavBar/menu.png'),
  home: require('../assets/NavBar/home.png'),
  locWhite: require('../assets/NavBar/locWhite.png'),
  close: require('../assets/NavBar/close.png'),
  background: require('../assets/background.png'),
  stadiumView:require('../assets/StadiumView/stadiumView.png'),
  VideoPlayer : require('../assets/CandidMoments/videoPlayer.png'),
  ticket: require('../assets/menu/ticket.png'),
  seat: require('../assets/menu/seat.png'),
  traffic: require('../assets/menu/traffic.png'),
  drone: require('../assets/menu/drone.png'),
  live: require('../assets/menu/play.png'),
  gallery: require('../assets/menu/gallery.png'),
  reward: require('../assets/menu/reward.png'),
  settings: require('../assets/menu/settings.png'),
  googleStreetView : require("../assets/StadiumView/googleStreetView.png"),
  ticketOfMatch : require("../assets/ticket.png"),
  fullScreen : require("../assets/fullScreen.png"),
  ticketImg: require("../assets/Tickets/INDvsAUS.png"),
  aud1: require("../assets/CandidMoments/audience1.jpeg"),
  aud2: require("../assets/CandidMoments/audience2.jpeg"),
  aud3: require("../assets/CandidMoments/audience3.jpeg"),
  aud4: require("../assets/CandidMoments/audience4.jpeg"),
};
